language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis poetry
script: tox
before_deploy:
- poetry config pypi-token.pypi $PYPI_PASSWORD
- poetry build
deploy:
  provider: script
  script: poetry publish
  edge: true
  on:
    tags: true
    python: 3.8
env:
  global:
  - secure: MtAguUSDamdPQnhJ2tgjiFigbbb8chDdz/G7KCSX9X1gYF7zaFHLgQ2q/gec7+5FsMOyRv4OrgIQSfetRrEktlTOga7Xqr1/7q0qsQGJQucGuFjgGzVuzZLrryn0XlBZIyYMmhiCRYL2nuj6xS1CyrkvmM1MsCltXNi6DSKD1a7MOfMwvXXmj24CFOk2LDLK6WkJHJUm9eEIRt1N8FTpJwwOATFSuU/rOrG3TqBX7HJ/mhj+4KMEorvMHAlS3WgWE6FK5M+D4Sc2Y7nzgxoy9gklSM9+hOVLHDm9vSAr4CUtk+yo7Di12SJvYj+UqGp5YG070E7Zs8qijQNcOGUtKV1ca2W1c8+DVI7ejipDX6bCrxjJmnZngvQDHaL6oW5HZ4BkitksYEEHMxkzjGHRDmoqZy852FSktfn9gwp8TT0gBphHme+8d9/xdTTkROuTNpzEJpf10I9tapxQ/2o9J3EIuiJiSmgMl8HxhC6NFZ8oZqjY/flBiQc+SyYCNT5nFQ04te1/HThZuU0rk30GrvMWmItxVZGmSxm+oIr6ObrvPDDn/pjcJhvgy4L9CcV2NE/Q7/BZj0V+bHMJ0U05Q5BhgWjHVaG5BTByURuvYF6D4S66vVCz/DdYPs18qvSqBhbaPo6duaFJsZvY2VhsnvwID59xEF+1yevwxplG3HA=
